use crate::stack::Stack;

#[derive(Debug)]
#[repr(C, packed)]
pub struct Settler {
    pos: (u16, u16),
    settler: SettlerType,
    team: u8,
}

#[derive(Clone, Copy, Debug)]
#[repr(u32)]
pub enum SettlerType {
    Carrier(Option<Stack>) = 1,
    Planer,
    Builder,
    Woodcutter,
    Stonecutter,
    Forester,
    Farmergrain,
    FarmerAnimals,
    Fisher,
    Waterworker,
    Hunter,
    SawmillWorker,
    Smelter,
    Mineworker,
    Smith,
    Miller,
    Baker,
    Butcher,
    ShipyardWorker,
    Healer,
    CharcoalMaker,
    AmmoMaker,
    VehicleMaker,
    Vintner,
    Beekeeper,
    Meadmaker,
    Agavefarmer,
    TquilaMaker,
    SwordsmanLevel1,
    SwordsmanLevel2,
    SwordsmanLevel3,
    BowmanLevel1,
    BowmanLevel2,
    BowmanLevel3,
    MedicLevel1,
    MedicLevel2,
    MedicLevel3,
    AxeWarriorLevel1,
    AxeWarriorLevel2,
    AxeWarriorLevel3,
    BlowgunWarriorLevel1,
    BlowgunWarriorLevel2,
    BlowgunWarriorLevel3,
    SquadLeader,
    Priest,
    Saboteur,
    Pioneer,
    Thief,
    Geologist,
    Gardener,
    Landscaper,
    DarkGardener,
    MushroomFarmer,
    Shaman,
    SlavedSettler,
    TempleServant,
    AngelLevel1,
    AngelLevel2,
    AngelLevel3,
    Donkey,
    BackpackCatalpultistLevel1,
    BackpackCatalpultistLevel2,
    BackpackCatalpultistLevel3,
    SunflowerFarmer,
    SunOilMaker,
    ManacopterMaster,
    //UNK68 = 68, // The first 6 entities of a game are this. Maybe the spawn flags set in the editor?
    //UNK69 = 69, // Probably door swordman of a tower
}
